# Generated by Django 2.2.16 on 2023-04-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20230405_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата окончания мероприятия', null=True, verbose_name='Дата окончания'),
        ),
    ]
