# Generated by Django 2.2.16 on 2023-04-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_comment_estimation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='estimation',
        ),
    ]
